language: ruby
cache: bundler
rvm:
- 2.1.0
env:
  global:
  - AMAZON_S3_BUCKET=slnz_bundle_cache
  - AMAZON_ACCESS_KEY_ID=AKIAJ7634GY5G6ZLG2ZA
  - secure: "m4HxMsqP5Re8NskI+rnotYaWFuEsTx+g5bDAoSZiRaRFQiPfWxNepdo/aR5It+h57aytcpnwSX8cpUxSEMqYycyJ9+AA3UUije04kWhf6DpcjNCi9LwIrqXnShIKIJwqeTHIXIv0vZFaXUMpX0PUHCEvebQACRcLrN/ij6+3M7g="
install:
- script/cached-bundle install --deployment --without development
before_script:
- psql -c 'create database creatr_api_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- cp .env.travis .env
- bundle exec rake db:migrate RAILS_ENV=test
script:
- RAILS_ENV=test bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: "YdSzaHpoAjgZ5uql38lg0m0Svw2soepIBWH7vQzbvl/VXc8DVHPdaOcQIbSPJU6Oyo/56Bpp0BLbxPo6X3tVnJS2e06OHZxC9nEqOUT4tsR6S3wSeN8bFbPTnSH9r+Ay7iU0Q+4niedRNat1WY+U98aRo5KincTwQrlJ/ut6R1c="
  app:
    master: creatr-api-staging
    production: creatr-api
  run:
    - "rake db:migrate"
    - restart
    - "rake cleanup"
  on:
    repo: slnz/creatr_api
addons:
  code_climate:
    repo_token:
      secure: "K9bHHh7Ib/TSXVPRYuAdL8yukkfshSK12bDE0M9LGpfy337fSjyoLMmX7kJh7F3vZCXCDwu94z9K40uSMFlmRr7FYZlgt0N7vTb7Zt5AjtJXoZKyflX1Yr+vP2Poql4JAJRgl+FDkBz0RlEWPtZFhZWkYQSWy23CBWItzKbGLvs="
notifications:
  flowdock:
    secure: VxM2wEGKNn53R28HSUM1ZTc39XUTOfe203kNf9C8Upv+B0ValbeYOTPeqelgK6+qMwDIlSZu6on0zHINVhzHsQDH+3EY6micZP8OCAgHFGGPe0/GPujZA+lY1by3OBlUVg7GJgGBu0qAg62UNFZwbDWMTb7EPMCnN4KCcLn2hkc=
